### PR TITLE
Fixed wrong commit for itl_hazard_mgr

### PR DESCRIPTION
**Pull request by Farossco**
Strangely, the revision in the manifest for hazard-mgr referred to nothing existent. This is now fixed. This correspond to the second initial commit.

### CODE REVIEW

**Comment by GiulianoFranchetto** [comment]
Commit d5e1f57986f3ff5d4ba1a5f4bf55ef5f30d68845 refers to the first commit on the dev branch, which has pretty much nothing in it.
I'm not sure this is what you want.
If you want to stay up-to-date with your ```dev``` branch, replace the value of ```revision``` to ```dev```

**Review by GiulianoFranchetto — CHANGES_REQUESTED** [review]
Commit d5e1f57986f3ff5d4ba1a5f4bf55ef5f30d68845 refers to the first commit on the dev branch, which has pretty much nothing in it.
I'm not sure this is what you want.
If you want to stay up-to-date with your ```dev``` branch, replace the value of ```revision``` to ```dev```

**Comment by Farossco** [comment]
I think it refers to an overwritten commit because the first commit is 76c7bc5fa87b87b016d83c0866ad1a96aa6cacaa now. This is necessary for west to correctly fetch the repo, otherwise, it gives an error.

**Comment by GiulianoFranchetto** [comment]
Try to either set ```dev``` as revision, or the latest commit on the dev branch for now ```ae5c44194e84b901810de1256ef5f124dbf5e8ee```.
I cannot accept this pull request with the commit revision you put on the manifest, as we will need another unnecessary PR to fix the revision once more

**Comment by Farossco** [comment]
Ok ça marche, je vais faire une branche dev-stable pour éviter de parasiter tout le monde avec des bêtises

**Pull request closed without merging**
